name = "btc-price-alert-bot"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV namespace for storing bot state
[[kv_namespaces]]
binding = "BTC_ALERT_KV"
id = "b706c4d8de7b46fcb9c81dd47597715f"

# Cron trigger to check price every 30 seconds
[triggers]
crons = ["*/30 * * * *"]  # Every 30 seconds

# Environment variables (set these in Cloudflare dashboard)
[vars]
PRICE_DELTA_USD = "500"
DRY_RUN = "0"

# Secrets (set these using wrangler secret put)
# TELEGRAM_BOT_TOKEN = "your-bot-token"
# TELEGRAM_CHAT_ID = "your-chat-id"